# Generated by Django 4.0.4 on 2022-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droid',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
