# Generated by Django 4.0.4 on 2022-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_droid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droid',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='droid',
            name='master',
            field=models.CharField(max_length=100, verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='droid',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='droid',
            name='planet',
            field=models.CharField(max_length=50, verbose_name='Планета'),
        ),
    ]
