# Generated by Django 4.0.4 on 2022-05-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_30', '0002_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriplion',
            new_name='description',
        ),
    ]
